---
Name: elementalflexsliderblockconfig
---
DNADesign\Elemental\Controllers\ElementController:
  default_styles:
    - cwchong/elemental-flexsliderblock:client/dist/styles/flexslider.css
    - cwchong/elemental-flexsliderblock:client/dist/styles/frontend.css